version: 2.1

jobs:
  backend:
    docker:
      - image: circleci/node:14

    # working_directory: ~/Backend_NodeJS

    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: cd Backend_NodeJS && npm install
      - run:
          name: Run Tests
          command: cd Backend_NodeJS && npm run test

  frontend:
    docker:
      - image: circleci/node:14

    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: cd frontend/revive-gallery-app && npm install
      - run:
          name: Run Tests
          command: cd frontend/revive-gallery-app && npm test
      - run:
          name: Create Build
          command: cd frontend/revive-gallery-app && npm run build

  # deploy:
  #   docker:
  #     - image: circleci/node:14

  #   steps:
  #     - run:
  #         name: Start Backend_NodeJS
  #         command: cd Backend_NodeJS && npm start
  #     - run:
  #         name: Start frontend
  #         command: cd frontend/revive-gallery-app && npm start


workflows:
  version: 2
  build_and_deploy:
    jobs:
      - backend
      - frontend:
          requires:
            - backend
      # - deploy:
      #     requires:
      #       - backend
      #       - frontend


